name: tfa.dev.infra

on:
  push:
    paths:
      - "infra/**"
      - ".github/workflows/**"
    branches: [develop]
  workflow_dispatch: {}

jobs:
  tfa-dev-tf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_TFA_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TFA_DEV_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Configure Terraform v0.15.3
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.3
      
      - name: Terraform Configuration
        run: |
          terraform -version
        shell: bash
      
      - name: Terraform Init Network Dev
        run: |
          terraform init -backend=true -backend-config=01-network/env/dev/backend.tfvars
        shell: bash

      - name: Terraform Plan Network Dev
        id: plan
        run: | 
          terraform plan
        shell: bash

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}