name: tfa.dev.infra

on:
  push:
    paths:
      - "infra/**"
      - ".github/workflows/**"
    branches: [develop]
  workflow_dispatch: {}

jobs:
  tfa-dev-tf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_TFA_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TFA_DEV_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Configure Terraform v0.15
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.1
      
      - name: Terraform Init Network Dev
        run: cd 01-network/env/dev && terraform init -backend=true -backend-config=backend.tfvars ../..

      - name: Terraform Plan Network Dev
        run: | 
          cd 01-network/env/dev
          terraform plan ../..