name: tfa.dev.infra

on:
  push:
    paths:
      - "infra/**"
      - ".github/workflows/**"
    branches: [develop]
  workflow_dispatch: {}

jobs:
  tfa-dev-tf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

#      - name: Terraform Security Scan
#        uses: triat/terraform-security-scan@v2.0.2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_TFA_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TFA_DEV_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Configure Terraform v0.15.3
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.3
          terraform_wrapper: false
      
      - name: Check Terraform fmt
        run: |
          terraform fmt -diff -check -recursive
        shell: bash
      
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run TFLint
        run: tflint -f compact
      
      - name: Terraform Init Network Dev
        run: |
          terraform init -input=false -backend=true -backend-config="env/dev/backend.tfvars"
        shell: bash
        working-directory: infra/01-network
      
      - name: Terraform Validate Network
        run: |
          terraform validate
        working-directory: infra/01-network
        shell: bash

      - name: Terraform Plan Network Dev
        id: tfplan
        run: |
          terraform plan -input=false -var-file="env/dev/terraform.tfvars"
          # terraform plan -var-file="env/dev/terraform.tfvars" -out terraform.plan
          # terraform show -json terraform.plan | tee terraform.json
        shell: bash
        working-directory: infra/01-network